"""Launch MO2 (or any Windows tool) under the game's Proton prefix — ModSync's
own durable launch, instead of MO2-LINT's Steam redirector.

We run the game's Proton inside its required Steam Linux Runtime (pressure-vessel)
pointed at the game's *existing* prefix — the same way Steam launches it, but
driven by us, so the launch doesn't depend on a Steam launch option (which Steam
rewrites out of ``appinfo.vdf``).
"""

from __future__ import annotations

from pathlib import Path


def find_proton(steam_root: Path, appid: int) -> Path | None:
    """The Proton install the game actually uses, read from its prefix's
    ``config_info`` (the authoritative signal Steam itself wrote)."""
    config_info = steam_root / "steamapps" / "compatdata" / str(appid) / "config_info"
    if config_info.exists():
        for line in config_info.read_text(errors="replace").splitlines():
            if "/files/" in line:
                root = Path(line.split("/files/")[0])
                if (root / "proton").exists():
                    return root
    # Fallback: any Proton-like tool, preferring Experimental, then newest name.
    found: list[Path] = []
    for base in (
        steam_root / "steamapps" / "common",
        steam_root / "compatibilitytools.d",
        Path.home() / ".steam/root/compatibilitytools.d",
    ):
        if base.is_dir():
            found += [d for d in base.iterdir() if (d / "proton").exists()]
    found.sort(key=lambda d: ("experimental" not in d.name.lower(), d.name.lower()))
    return found[0] if found else None


def find_runtime(steam_root: Path) -> Path | None:
    """The Steam Linux Runtime entry script current Proton needs (sniper)."""
    for name in ("SteamLinuxRuntime_sniper", "SteamLinuxRuntime_soldier"):
        run = steam_root / "steamapps" / "common" / name / "run"
        if run.exists():
            return run
    return None


def compat_env(steam_root: Path, appid: int) -> dict[str, str]:
    return {
        "STEAM_COMPAT_DATA_PATH": str(steam_root / "steamapps" / "compatdata" / str(appid)),
        "STEAM_COMPAT_CLIENT_INSTALL_PATH": str(steam_root),
    }


def build_launch(
    steam_root: Path, appid: int, exe: Path
) -> tuple[list[str], dict[str, str]] | None:
    """``(argv, extra_env)`` to run ``exe`` under the game's Proton + runtime, or
    ``None`` if no Proton could be found."""
    proton = find_proton(steam_root, appid)
    if proton is None:
        return None
    proton_cmd = [str(proton / "proton"), "run", str(exe)]
    runtime = find_runtime(steam_root)
    argv = [str(runtime), "--", *proton_cmd] if runtime else proton_cmd
    return argv, compat_env(steam_root, appid)


def _shquote(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def launch_script(steam_root: Path, appid: int, exe: Path) -> str:
    """A standalone POSIX script that launches ``exe`` under the game's Proton."""
    built = build_launch(steam_root, appid, exe)
    if built is None:
        raise RuntimeError("could not find the Proton this game uses")
    argv, env = built
    lines = [
        "#!/bin/sh",
        "# Launch Mod Organizer 2 under the game's Proton prefix.",
        "# Generated by ModSync — replaces the MO2-LINT Steam redirector.",
        "",
    ]
    lines += [f'export {k}={_shquote(v)}' for k, v in env.items()]
    lines += ["", "exec " + " ".join(_shquote(a) for a in argv) + ' "$@"', ""]
    return "\n".join(lines)
