"""Convert Mulderland's open-source Skyrim downgrader recipe into ModSync's index.

Mulderland (https://www.mulderland.com) publishes a Windows installer that
downgrades Skyrim SE from the current Steam build to earlier ones by applying
xdelta3 patches. The installer is generated from an NSIS script kept in the
public ``Mulderland/MulderLoad`` GitHub repo, and the patches live on a public
CDN. Everything the installer does is portable — download, verify SHA1, extract
a 7z, run xdelta3 — so ModSync does it natively on Linux instead of running
the .exe under Proton.

This module turns that NSIS script into a plain JSON **recipe index**. ModSync
reads the index at runtime, so when Bethesda ships a patch and Mulderland
updates the recipe (historically within hours), ModSync users get the new
downgrade path without a ModSync release. The index is regenerated by a
scheduled GitHub Action (see ``scripts/build_recipe_index.py``).

What we extract from the script:

* the **source** game version the patches apply to, and the SHA1 of its main
  executable, from the version check in ``OnSelectedFile``;
* one **target** per ``Section ... version_X_Y_Z`` block;
* inside each target, one archive per Steam depot: ``DOWNLOAD_1`` for a single
  file (SHA1 of the whole file) and ``DOWNLOAD_RANGE`` for split archives
  (``.001``…``.NNN``; the SHA1 covers the first part only, as in the script's
  ``DownloadRange`` function);
* the ``${If} $Game_Language == "…"`` blocks that select language depots.

The parser is deliberately line-oriented and tolerant: it only needs the
handful of constructs above and ignores everything else.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

SOURCE_REPO = "Mulderland/MulderLoad"
SOURCE_PATH = "games/the-elder-scrolls-5-skyrim-special-edition/steam-downgrader.nsi"
SOURCE_REF = "main"

# The installer's human language names -> Steam's language codes (the values
# Steam writes to ``UserConfig/language`` in the appmanifest and to
# ``depots/<id>/config/language`` in appinfo.vdf).
LANGUAGE_CODES: dict[str, str] = {
    "English": "english",
    "French": "french",
    "Italian": "italian",
    "German": "german",
    "Spanish": "spanish",
    "Russian": "russian",
    "Polish": "polish",
    "Japanese": "japanese",
    "Chinese (Traditional)": "tchinese",
    "Chinese (Simplified)": "schinese",
    "Korean": "koreana",
    "Portuguese (Brazil)": "brazilian",
}

_SECTION_RE = re.compile(r'^\s*Section(?:\s+/o)?\s+"([^"]*)"\s+(version_\w+)\s*$')
_SECTION_END_RE = re.compile(r"^\s*SectionEnd\b")
_LANG_IF_RE = re.compile(r'\$\{(?:If|ElseIf)\}\s+\$Game_Language\s*==\s*"([^"]+)"')
_LANG_ENDIF_RE = re.compile(r"\$\{EndIf\}")
_DL_RANGE_RE = re.compile(
    r'DOWNLOAD_RANGE\s+"([^"]+)"\s+"([^"]+)"\s+"([0-9a-fA-F]*)"\s+(\d+)'
)
_DL_1_RE = re.compile(r'DOWNLOAD_1\s+"([^"]+)"\s+"([^"]+)"\s+"([0-9a-fA-F]*)"')
_SOURCE_VERSION_RE = re.compile(r"Game version:\s*v(\d+(?:\.\d+)+)")
_SOURCE_SHA1_RE = re.compile(
    r'FILE_HASH_EQUALS\s+"\$INSTDIR\\([^"\\]+\.exe)"\s+"([0-9a-fA-F]{40})"'
)
_DEPOT_FROM_FILENAME_RE = re.compile(r"^(\d+)\.7z(?:\.\d{3})?$")
_ADDSIZE_RE = re.compile(r"^\s*AddSize\s+(\d+)")


class RecipeParseError(ValueError):
    pass


@dataclass
class Part:
    url: str
    sha1: str | None  # None for parts after the first of a split archive

    def as_dict(self) -> dict[str, Any]:
        return {"url": self.url, "sha1": self.sha1}


@dataclass
class DepotPatch:
    depot: str
    archive: str  # filename the installer would save, e.g. "489831.7z.001"
    parts: list[Part]
    language: str | None  # Steam language code, None for the base (all-language) depots

    def as_dict(self) -> dict[str, Any]:
        return {
            "archive": self.archive,
            "language": self.language,
            "parts": [p.as_dict() for p in self.parts],
        }


@dataclass
class Target:
    version: str
    title: str
    depots: dict[str, DepotPatch] = field(default_factory=dict)
    estimated_kib: int | None = None  # the installer's AddSize (KiB), if given

    def as_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "estimated_kib": self.estimated_kib,
            "depots": {k: v.as_dict() for k, v in sorted(self.depots.items())},
        }


@dataclass
class Recipe:
    source_version: str
    source_exe: str
    source_exe_sha1: str
    targets: dict[str, Target]

    def as_dict(self) -> dict[str, Any]:
        return {
            "from": {
                "version": self.source_version,
                "exe": self.source_exe,
                "exe_sha1": self.source_exe_sha1,
            },
            "targets": {k: v.as_dict() for k, v in self.targets.items()},
        }


def _version_from_section_id(section_id: str) -> str | None:
    # version_1_6_1170 -> 1.6.1170 ; version_common -> None
    tail = section_id[len("version_") :]
    if not tail or not all(p.isdigit() for p in tail.split("_")):
        return None
    return ".".join(tail.split("_"))


def _expand_range(url: str, filename: str, sha1: str, nparts: int) -> list[Part]:
    if not url.endswith(".001") or not filename.endswith(".001"):
        raise RecipeParseError(f"DOWNLOAD_RANGE without .001 suffix: {url}")
    if nparts < 1:
        raise RecipeParseError(f"DOWNLOAD_RANGE with {nparts} parts: {url}")
    base = url[:-3]
    parts = [Part(url, sha1.lower() or None)]
    for i in range(2, nparts + 1):
        parts.append(Part(f"{base}{i:03d}", None))
    return parts


def parse(text: str) -> Recipe:
    source_version: str | None = None
    source_exe: str | None = None
    source_sha1: str | None = None
    targets: dict[str, Target] = {}

    current: Target | None = None
    language: str | None = None  # Steam code of the active language block
    lang_depth = 0

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue

        if source_version is None:
            m = _SOURCE_VERSION_RE.search(line)
            if m:
                source_version = m.group(1)
        if source_sha1 is None:
            m = _SOURCE_SHA1_RE.search(line)
            if m:
                source_exe, source_sha1 = m.group(1), m.group(2).lower()

        m = _SECTION_RE.match(raw)
        if m:
            title, section_id = m.group(1), m.group(2)
            version = _version_from_section_id(section_id)
            current = Target(version, title) if version else None
            if current:
                targets[version] = current
            language, lang_depth = None, 0
            continue
        if _SECTION_END_RE.match(raw):
            current = None
            language, lang_depth = None, 0
            continue
        if current is None:
            continue

        m = _ADDSIZE_RE.match(raw)
        if m:
            current.estimated_kib = int(m.group(1))
            continue

        m = _LANG_IF_RE.search(line)
        if m:
            name = m.group(1)
            code = LANGUAGE_CODES.get(name)
            if code is None:
                raise RecipeParseError(f"unknown language name in recipe: {name!r}")
            if "${If}" in line:
                lang_depth += 1
            language = code
            continue
        if _LANG_ENDIF_RE.search(line):
            if lang_depth:
                lang_depth -= 1
            if lang_depth == 0:
                language = None
            continue

        m = _DL_RANGE_RE.search(line)
        parts: list[Part] | None = None
        filename = ""
        if m:
            url, filename, sha1, n = m.group(1), m.group(2), m.group(3), int(m.group(4))
            parts = _expand_range(url, filename, sha1, n)
        else:
            m = _DL_1_RE.search(line)
            if m:
                url, filename, sha1 = m.group(1), m.group(2), m.group(3)
                parts = [Part(url, sha1.lower() or None)]
        if parts is None:
            continue
        dm = _DEPOT_FROM_FILENAME_RE.match(filename)
        if not dm:
            raise RecipeParseError(f"cannot infer depot id from archive name {filename!r}")
        depot = dm.group(1)
        if depot in current.depots:
            raise RecipeParseError(
                f"depot {depot} listed twice for target {current.version}"
            )
        current.depots[depot] = DepotPatch(depot, filename, parts, language)

    if not source_version or not source_sha1 or not source_exe:
        raise RecipeParseError("could not find the source game version / exe SHA1 check")
    if not targets:
        raise RecipeParseError("no version_* sections found")
    for t in targets.values():
        if not t.depots:
            raise RecipeParseError(f"target {t.version} has no downloads")
    return Recipe(source_version, source_exe, source_sha1, targets)


def build_index(
    recipe: Recipe,
    static: dict[str, Any],
    *,
    source_commit: str | None,
    generated_at: str,
) -> dict[str, Any]:
    """Merge the parsed recipe with ModSync's static Steam knowledge into the
    JSON document ModSync consumes at runtime."""
    index: dict[str, Any] = {
        "schema": 1,
        "generated_at": generated_at,
        "game": static["game"],
        "source": {
            "provider": "mulderload",
            "repo": SOURCE_REPO,
            "path": SOURCE_PATH,
            "ref": SOURCE_REF,
            "commit": source_commit,
            "url": f"https://github.com/{SOURCE_REPO}/blob/{source_commit or SOURCE_REF}/{SOURCE_PATH}",
            "homepage": static.get("source_homepage"),
        },
        **recipe.as_dict(),
        "post_steps": static.get("post_steps", []),
        "steam": static.get("steam", {}),
    }
    return index
